In [ ]:
import numpy as np
arr0d=np.array(10)
print(arr0d)
print(arr0d.ndim)
print(arr0d.ndim)
arr1d=np.array([1,2,3,4,5])
print(arr1d)
print(arr1d.ndim)
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.ndim)
arr3d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3d)
print(arr3d.ndim)

10
0
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
#using built in function
zeros=np.zeros((2,3))
print(zeros)

ones=np.ones((2,3))
print(ones)

random_arr=np.random.random((2,2))
print(random_arr)

print(np.eye((3)))

print(np.linspace(0,1,5))

print(np.arange(0,22,3))

print(np.random.rand(2,3))

print(np.random.randn(2,3))

print(np.random.randint(1,10,(2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.94194005 0.46703786]
 [0.38475997 0.84620664]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[ 0  3  6  9 12 15 18 21]
[[0.69233193 0.39241098 0.25089902]
 [0.71113234 0.22556289 0.12044531]]
[[-2.88002195  1.58954648  1.0765408 ]
 [-0.8373933  -0.20209362 -0.50720275]]
[[8 3 5]
 [3 6 2]]


In [ ]:
#array attributes
arr=np.arange(1,10,2)
print(arr)

arr1=np.array([[1,2,3],[4,5,6]])
print("shape",arr1.shape)

print("size",arr1.size)

print("data type",arr1.dtype)

print("dimensions",arr1.ndim)

[1 3 5 7 9]
shape (2, 3)
size 6
data type int64
dimensions 2


In [ ]:
#import numpy as np
temp_data=np.array([[22,25,20],[24,26,23]])

print(temp_data)
print()
print(temp_data.shape)
print()
print(temp_data.size)
print()
print(temp_data.dtype)
print()
print(temp_data.ndim)
print()
gh3=np.array([21,23,22])

updated_temp_data=np.vstack([temp_data,gh3])

sensor_error_flags=np.zeros((2,3))

greenhouse_identity=np.eye(3)

print(updated_temp_data)
print()
print(sensor_error_flags)
print()
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]

(2, 3)

6

int64

2

[[22 25 20]
 [24 26 23]
 [21 23 22]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [ ]:
#indexing and slicing

arr=np.array([[1,2,3],[4,5,6]])

print(arr[0,0])

print(arr[0,2])
print(arr[:])
print(arr[:,1:])

1
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print(shipments[0,2])
print(shipments[1,6])
print(shipments[:,0:5])
print(shipments[:,5:7])
print(shipments[0,2:6])
shipments[0,5]=10
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
55
75
[[50 60 55 70 65]
 [40 45 50 60 55]]
[[80 90]
 [70 75]]
[55 70 65 80]
[[50 60 55 70 65 10 90]
 [40 45 50 60 55 70 75]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
#Arithematic
a=np.array([22,21,22,25])
b=np.array([26,24,34,12])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
#scaler operations
print(a*3+b*2)

a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[3,2],[1,6],[5,4]])
r=np.dot(a1,b1)
print(r)

b=5
print(a+b)

[48 45 56 37]
[ -4  -3 -12  13]
[572 504 748 300]
[0.84615385 0.875      0.64705882 2.08333333]
[22 21 22  1]
[ 9191333876016873472 -4075458838872914655   349424675048128512
    59604644775390625]
[118 111 134  99]
[[20 26]
 [47 62]]
[27 26 27 30]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
#inbuilt operations
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

print(np.exp(a))
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.expm1(a))

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.arcsin(a))
print(np.arccos(a))
print(np.arctan(a))

print(np.round(a))
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))

print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.mean(a))
print(np.var(a))
print(np.sum(a))
print(np.prod(a))

print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a,b))
print(np.logical_xor(a,b))

print(np.greater(a,b))
print(np.less(a,b))
print(np.equal(a,b))
print(np.not_equal(a,b))
print(np.greater_equal(a,b))
print(np.less_equal(a,b))

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))
print(np.bitwise_xor(a,b))
print(np.invert(a))

print("sum",np.sum(a))
print("mean",np.mean(a))
print("standrad deviation",np.std(a))
print("max",np.max(a))
print("min",np.min(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[ 1.71828183  6.3890561  19.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]
[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
1
3
0.816496580927726
2.0
0.6666666666666666
6
6
[ True  True  True]
[ True  True  True]
[0 0 0]
[ True  True  True]
[ True  True  True]
[False False False]
[False False False]
[ True  True  True]
[ True  True  True]
[False False False]
[0 0 0]
[1 2 3]
[1 2 3]
[-2 -3 -4]
sum 6
mean 2.0
standrad deviation 0.816496580927726
max 3
min 1


/tmp/ipython-input-3599613537.py:21: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))
/tmp/ipython-input-3599613537.py:22: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(a))


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
import numpy as np

# -----------------------------
# Step 1: Create arrays
# -----------------------------
# Example data: 3 farms × 4 panels × 3 hours
farmA = np.array([
    [10, 12, 15],
    [14, 11, 12],
    [8,  10, 11],
    [18, 20, 19]
], dtype=float)

farmB = np.array([
    [7,  9, 11],
    [6,  8, 9],
    [20, 24, 23],
    [5,  6, 7]
], dtype=float)

farmC = np.array([
    [13, 10, 19],
    [12, 15, 22],
    [8,   2,  2],
    [25, 26, 24]
], dtype=float)

# Stack into 3D array (3,4,3)
production_all = np.stack([farmA, farmB, farmC])
print("production_all:\n", production_all)
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Ndim:", production_all.ndim)

# -----------------------------
# Step 2: Per-farm totals
# -----------------------------
total_per_farm = production_all.sum(axis=(1,2))
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm  = production_all.std(axis=(1,2))
var_per_farm  = production_all.var(axis=(1,2))

print("\nTotal per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# -----------------------------
# Step 3: Weighted per-panel
# -----------------------------
hour_weights = np.array([0.5, 1.0, 0.75])   # (3,)
weighted_per_panel = np.dot(production_all, hour_weights)  # (3,4)
print("\nWeighted per-panel (per farm):\n", weighted_per_panel)

# -----------------------------
# Step 4: Broadcasting adjustment
# -----------------------------
# Add +0.5 to all Farm B panels (farm index 1)
production_all[1] += 0.5
print("\nFarm B after calibration:\n", production_all[1])

# -----------------------------
# Step 5: Normalization (z-score)
# -----------------------------
farm_means = production_all.mean(axis=(1,2), keepdims=True)
farm_stds  = production_all.std(axis=(1,2), keepdims=True)
normalized = (production_all - farm_means) / farm_stds
print("\nNormalized shape:", normalized.shape)

# -----------------------------
# Step 6: Apply ufuncs
# -----------------------------
exp_vals   = np.exp(normalized)
log_vals   = np.log1p(np.abs(normalized))   # safe log
sin_vals   = np.sin(normalized)
cos_vals   = np.cos(normalized)
rounded    = np.round(normalized)

print("\nSum exp:", np.sum(exp_vals))
print("Mean sin:", np.mean(sin_vals))
print("Rounded example:\n", rounded[0])

# -----------------------------
# Step 7: Comparison & logical masks
# -----------------------------
high_output = production_all > 20
even_hours_mask = np.arange(3) % 2 == 0   # hours 0,2
even_hours_mask = even_hours_mask.reshape(1,1,3)

mask_and = np.logical_and(high_output, even_hours_mask)
print("\nHigh output mask:\n", high_output.astype(int))
print("Combined mask (high & even hours):\n", mask_and.astype(int))

# -----------------------------
# Step 8: Bitwise ufuncs
# -----------------------------
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
], dtype=int)

bit_and = np.bitwise_and(alerts, high_output.astype(int))
bit_or  = np.bitwise_or(alerts, high_output.astype(int))
print("\nBitwise AND example:\n", bit_and[0])
print("Bitwise OR example:\n", bit_or[0])

# -----------------------------
# Step 9: Panel totals & maintenance
# -----------------------------
panel_totals_per_farm = production_all.sum(axis=2)   # (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)

# -----------------------------
# Step 10: Final KPIs
# -----------------------------
overall_total = production_all.sum()
peak_idx = np.argmax(production_all)
peak_value = production_all.flatten()[peak_idx]
farm, panel, hour = np.unravel_index(peak_idx, production_all.shape)
avg_per_panel = production_all.mean(axis=(0,2))   # average across farms & hours

print("\nOverall total:", overall_total)
print("Peak production:", peak_value, "at farm", farm, "panel", panel, "hour", hour)
print("Average per panel across all farms:", avg_per_panel)


production_all:
 [[[10. 12. 15.]
  [14. 11. 12.]
  [ 8. 10. 11.]
  [18. 20. 19.]]

 [[ 7.  9. 11.]
  [ 6.  8.  9.]
  [20. 24. 23.]
  [ 5.  6.  7.]]

 [[13. 10. 19.]
  [12. 15. 22.]
  [ 8.  2.  2.]
  [25. 26. 24.]]]
Shape: (3, 4, 3)
Size: 36
Dtype: float64
Ndim: 3

Total per farm: [160. 135. 178.]
Mean per farm: [13.33333333 11.25       14.83333333]
Std per farm: [3.72677996 6.63481977 8.12232862]
Var per farm: [13.88888889 44.02083333 65.97222222]

Weighted per-panel (per farm):
 [[28.25 27.   22.25 43.25]
 [20.75 17.75 51.25 13.75]
 [30.75 37.5   7.5  56.5 ]]

Farm B after calibration:
 [[ 7.5  9.5 11.5]
 [ 6.5  8.5  9.5]
 [20.5 24.5 23.5]
 [ 5.5  6.5  7.5]]

Normalized shape: (3, 4, 3)

Sum exp: 60.685866542125744
Mean sin: -0.06537665058213933
Rounded example:
 [[-1. -0.  0.]
 [ 0. -1. -0.]
 [-1. -1. -1.]
 [ 1.  2.  2.]]

High output mask:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 1]
  [0 0 0]
  [1 1 1]]]
Combined mask (hig

You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [ ]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

#tacking and splitting

a=np.array([1,2])
b=np.array([3,4])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

#advanced indexing
#a. boolean indexing
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])
#b. fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

#copy and view

arr=np.array([1,2,3])
print(arr)
view=arr.view()
view[0]=10
print(arr)

copy=arr.copy()
copy[0]=1
print(arr)

#saving and loading
#a. save to a file
arr=np.array([1,2,3])
np.save('array.npy',arr)
#b. load fro a fle
loaded_arr=np.load('array.npy')
print(loaded_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]
[4 5 6]
[10 30]
[1 2 3]
[10  2  3]
[10  2  3]
[1 2 3]


In [ ]:
import numpy as np
arr=np.arange(10,51)
randing=np.random.rand(3)
print(randing)

print(arr.shape)
print(arr.size)
print(arr.dtype)

arr=arr+5
print(arr)

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[1,2,3]])
print(arr1*arr2)

arr=np.arange(1,26)
arr=arr.reshape(5,5)

print(arr[0,:])
print(arr[:,4])
print(arr[:3,:3])

arr=np.random.randint(10,101,size=10)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())

arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)

arr=np.ones(3)
print(arr)
arr1=[1,2,3]
arr=arr+arr1
print(arr)

arr3=np.random.randint(1,50,size=15)
arr2=arr3[arr3%5==0]
print(arr2)

p=np.array([[1,2,3],[4,5,6]])
p1=np.array([[9,8,7],[6,5,4]])
print(p*p1)

o=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
o1=o.reshape(4,4)
dia=o1[np.arange(4),np.arange(4)]
print(dia)

[0.4698475  0.07312912 0.16006868]
(41,)
41
int64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 4 10 18]
 [ 4 10 18]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
95
12
59.3
31.92506851989515
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1. 1. 1.]
[2. 3. 4.]
[45 40 30]
[[ 9 16 21]
 [24 25 24]]
[ 1  6 11 16]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.